# Builds/deploys a API server and Postgres database, configured to talk to each other.
services:

  backend:
    container_name: 'atoywebapi'
    image: atoywebapi:edge
    build:
      context: .
    ports:
    - '8080:8080'
    expose:
    - 8080
    environment:
    - DATABASE_URL=postgresql://username:password@database:5432/databasename
    restart: on-failure
    depends_on:
    - database

  database:
    container_name: atoywebapi-db
    image: postgres:17.2
    restart: always
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=username
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=databasename
